apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-triggerer
  labels:
    app: airflow-triggerer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-triggerer
  template:
    metadata:
      labels:
        app: airflow-triggerer
    spec:
      containers:
      - name: triggerer
        image: ghcr.io/dnbnero/airflow
        envFrom:
          - secretRef:
              name: airflow-secrets
        args:
          - airflow
          - triggerer
        volumeMounts:
            - name: config
              mountPath: "/opt/airflow/config/"
              readOnly: true
      volumes:
        - name: config
          projected:
            sources:
              - configMap:
                  name: airflow-cfg
